### Config file for 4_dereplication_mapping.snakefile
### RE 05/2023

ani: 0.98
dmb: DMBATCH
codedir: /projects/ehi/data/0_Code/EHI_bioinformatics_EHI_VERSION/workflow
workdir: /projects/ehi/data/DMB/DMBATCH
magdir: /projects/ehi/data/DMB/DMBATCH/mags
logdir: /projects/ehi/data/RUN/DMBATCH/logs
GTDB_data: /projects/ehi/data/release214